### ISSUE TITLE
Simple Operator Example

### ISSUE THREAD

**Issue by premdass** [microbean/microbean-kubernetes-controller-cdi#2]
Hi @ljnelson 
Would you be able to provide a simple operator example written using your framework, so the whole concept of the framework can be better understood, Please?
Thanks,
P

**Comment by ljnelson** [comment]
I'd be happy to.  It may take me a while between real work and other open source work to get around to it.

For the background of the whole framework, you might be interested in [my blog series on the whole thing](https://lairdnelson.wordpress.com/2018/01/07/understanding-kubernetes-tools-cache-package-part-0/).

For a general approach, first [you need to define a qualifier annotation that is going to describe what sorts of Kubernetes objects you want to watch and is going to annotate your event observer](https://github.com/microbean/microbean-kubernetes-controller-cdi/blob/master/src/test/java/org/microbean/kubernetes/controller/cdi/TestEventDistribution.java#L115-L122).

Then you [define an observer method whose parameter is `org.microbean.kubernetes.controller.Event<? extends HasMetadata>` and which is annotated with that same annotation defined above](https://github.com/microbean/microbean-kubernetes-controller-cdi/blob/master/src/test/java/org/microbean/kubernetes/controller/cdi/TestEventDistribution.java#L91).

Then you [define a producer method annotated with the same annotation defined above that returns a `io.fabric8.kubernetes.client.dsl.Operation` of the proper kind](https://github.com/microbean/microbean-kubernetes-controller-cdi/blob/master/src/test/java/org/microbean/kubernetes/controller/cdi/TestEventDistribution.java#L84-L89).

That's it!

**Comment by ljnelson** [comment]
In the event that you are attending Oracle CodeOne this year, I am [giving a talk on this very subject](https://oracle.rainfocus.com/widget/oracle/oow18/catalogcodeone18?search=DEV5432).

**Comment by ljnelson** [comment]
Please see https://microbean.github.io/microbean-kubernetes-controller-cdi/examples.html.  There will be more.
